### ISSUE TITLE
检测和分割效果不如直接语义分割的

### ISSUE THREAD

**Issue by zhouzhubin** [xuebinqin/U-2-Net#169]
你好, 我们自己的数据集. 我和我同事训练, 我用的您的u2net, 我同事用的BiSeNet, 最终的测试的分割效果大不如u2net不如BiSeNet,这是什么原因

**Comment by xuebinqin** [comment]
Without the desciptions of tasks, dataset, input resolution, batch size and related info, we can’t give exact analysis. Usually, U^2-Net takes longer time in training than other models, because U^2-Net uses the dense supervision strategy. Besides, U^2-Net was orginally designed for binary class segmenation so that more kernel filters before the layer layer (sigmoid) may needed to achieve better performance on semantic multi-class segmentation.

**Comment by zhouzhubin** [comment]
您好,感谢您的回复.是同一个数据集, 类别就只有一类. 模型的输入都是320, 我训练了500个epcho, 我同事训练了100个.
